In [52]:
import pandas as pd
import numpy as np

In [53]:
# pandas는 날짜 생성 기능이 있다.
dates = pd.date_range('20190301', periods=6)
dates

DatetimeIndex(['2019-03-01', '2019-03-02', '2019-03-03', '2019-03-04',
               '2019-03-05', '2019-03-06'],
              dtype='datetime64[ns]', freq='D')

In [54]:
df = pd.DataFrame(np.random.randn(6,4), index = dates, columns=['A','B','C','D'])
df

A         B         C         D
2019-03-01  0.787596  1.117223  0.406246 -0.081113
2019-03-02  1.951820  1.354486 -0.600456  1.872849
2019-03-03 -0.977186 -1.290723  1.237134  0.368365
2019-03-04 -0.791070  0.664261  2.141459 -1.416075
2019-03-05 -0.810448  0.064461  0.129514  0.635390
2019-03-06  1.073196 -0.817408  0.386553  0.126255

In [55]:
print(type(df))
print(df.columns)
print(df.index)
print(df.values)

<class 'pandas.core.frame.DataFrame'>
Index(['A', 'B', 'C', 'D'], dtype='object')
DatetimeIndex(['2019-03-01', '2019-03-02', '2019-03-03', '2019-03-04',
               '2019-03-05', '2019-03-06'],
              dtype='datetime64[ns]', freq='D')
[[ 0.78759649  1.11722279  0.40624606 -0.08111293]
 [ 1.95182033  1.35448595 -0.60045635  1.87284902]
 [-0.97718621 -1.29072333  1.23713355  0.36836473]
 [-0.79106987  0.66426137  2.14145938 -1.41607472]
 [-0.81044826  0.0644606   0.12951416  0.6353901 ]
 [ 1.07319601 -0.81740786  0.38655297  0.12625465]]


In [56]:
# 개수, 평균, 표준 편차, 최댓값/최솟값 등을 정리해주는 .describe
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.205651  0.182050  0.616742  0.250945
std    1.230074  1.064283  0.951410  1.067420
min   -0.977186 -1.290723 -0.600456 -1.416075
25%   -0.805604 -0.596941  0.193774 -0.029271
50%   -0.001737  0.364361  0.396400  0.247310
75%    1.001796  1.003982  1.029412  0.568634
max    1.951820  1.354486  2.141459  1.872849

In [57]:
# 정렬하기
# df.sort_values(by='A')
df.sort_values(by='A', ascending=False)

A         B         C         D
2019-03-02  1.951820  1.354486 -0.600456  1.872849
2019-03-06  1.073196 -0.817408  0.386553  0.126255
2019-03-01  0.787596  1.117223  0.406246 -0.081113
2019-03-04 -0.791070  0.664261  2.141459 -1.416075
2019-03-05 -0.810448  0.064461  0.129514  0.635390
2019-03-03 -0.977186 -1.290723  1.237134  0.368365

In [58]:
print(type(df['A']))
df['A']

<class 'pandas.core.series.Series'>


2019-03-01    0.787596
2019-03-02    1.951820
2019-03-03   -0.977186
2019-03-04   -0.791070
2019-03-05   -0.810448
2019-03-06    1.073196
Freq: D, Name: A, dtype: float64

In [59]:
df[:3]

A         B         C         D
2019-03-01  0.787596  1.117223  0.406246 -0.081113
2019-03-02  1.951820  1.354486 -0.600456  1.872849
2019-03-03 -0.977186 -1.290723  1.237134  0.368365

In [60]:
df.loc['2019-03-01']

A    0.787596
B    1.117223
C    0.406246
D   -0.081113
Name: 2019-03-01 00:00:00, dtype: float64

In [61]:
df.loc['2019-03-01', ['A']]

A    0.787596
Name: 2019-03-01 00:00:00, dtype: float64

In [62]:
df.loc['2019-03-01', ['A','B']]

A    0.787596
B    1.117223
Name: 2019-03-01 00:00:00, dtype: float64

In [63]:
df.loc['2019-03-01':'2019-03-02', ['A','B']]

A         B
2019-03-01  0.787596  1.117223
2019-03-02  1.951820  1.354486

In [64]:
df.loc[:, ['A','B']]

A         B
2019-03-01  0.787596  1.117223
2019-03-02  1.951820  1.354486
2019-03-03 -0.977186 -1.290723
2019-03-04 -0.791070  0.664261
2019-03-05 -0.810448  0.064461
2019-03-06  1.073196 -0.817408

In [65]:
df.iloc[:3]

A         B         C         D
2019-03-01  0.787596  1.117223  0.406246 -0.081113
2019-03-02  1.951820  1.354486 -0.600456  1.872849
2019-03-03 -0.977186 -1.290723  1.237134  0.368365

In [66]:
df.iloc[0:2, 0:2]

A         B
2019-03-01  0.787596  1.117223
2019-03-02  1.951820  1.354486

In [67]:
df.iloc[[0,1,3], 0:2]

A         B
2019-03-01  0.787596  1.117223
2019-03-02  1.951820  1.354486
2019-03-04 -0.791070  0.664261

In [68]:
df.iloc[[0,1,3]]

A         B         C         D
2019-03-01  0.787596  1.117223  0.406246 -0.081113
2019-03-02  1.951820  1.354486 -0.600456  1.872849
2019-03-04 -0.791070  0.664261  2.141459 -1.416075

In [69]:
# 조건문 사용하기

In [70]:
df['A'] > 0

2019-03-01     True
2019-03-02     True
2019-03-03    False
2019-03-04    False
2019-03-05    False
2019-03-06     True
Freq: D, Name: A, dtype: bool

In [71]:
df[df['A']>0]

A         B         C         D
2019-03-01  0.787596  1.117223  0.406246 -0.081113
2019-03-02  1.951820  1.354486 -0.600456  1.872849
2019-03-06  1.073196 -0.817408  0.386553  0.126255

In [72]:
df>0

A      B      C      D
2019-03-01   True   True   True  False
2019-03-02   True   True  False   True
2019-03-03  False  False   True   True
2019-03-04  False   True   True  False
2019-03-05  False   True   True   True
2019-03-06   True  False   True   True

In [74]:
df[df>0]

A         B         C         D
2019-03-01  0.787596  1.117223  0.406246       NaN
2019-03-02  1.951820  1.354486       NaN  1.872849
2019-03-03       NaN       NaN  1.237134  0.368365
2019-03-04       NaN  0.664261  2.141459       NaN
2019-03-05       NaN  0.064461  0.129514  0.635390
2019-03-06  1.073196       NaN  0.386553  0.126255

In [76]:
# 행과 열의 변경
df2 = pd.DataFrame(df, columns=['A','B','C','D'])
df2

A         B         C         D
2019-03-01  0.787596  1.117223  0.406246 -0.081113
2019-03-02  1.951820  1.354486 -0.600456  1.872849
2019-03-03 -0.977186 -1.290723  1.237134  0.368365
2019-03-04 -0.791070  0.664261  2.141459 -1.416075
2019-03-05 -0.810448  0.064461  0.129514  0.635390
2019-03-06  1.073196 -0.817408  0.386553  0.126255

In [77]:
df['E'] = np.nan
df

A         B         C         D   E
2019-03-01  0.787596  1.117223  0.406246 -0.081113 NaN
2019-03-02  1.951820  1.354486 -0.600456  1.872849 NaN
2019-03-03 -0.977186 -1.290723  1.237134  0.368365 NaN
2019-03-04 -0.791070  0.664261  2.141459 -1.416075 NaN
2019-03-05 -0.810448  0.064461  0.129514  0.635390 NaN
2019-03-06  1.073196 -0.817408  0.386553  0.126255 NaN

In [78]:
df.loc['2019-03-02', ['E']] = 2
df

A         B         C         D    E
2019-03-01  0.787596  1.117223  0.406246 -0.081113  NaN
2019-03-02  1.951820  1.354486 -0.600456  1.872849  2.0
2019-03-03 -0.977186 -1.290723  1.237134  0.368365  NaN
2019-03-04 -0.791070  0.664261  2.141459 -1.416075  NaN
2019-03-05 -0.810448  0.064461  0.129514  0.635390  NaN
2019-03-06  1.073196 -0.817408  0.386553  0.126255  NaN

In [80]:
df['F'] = df['A'] + df['B']
df

A         B         C         D    E         F
2019-03-01  0.787596  1.117223  0.406246 -0.081113  NaN  1.904819
2019-03-02  1.951820  1.354486 -0.600456  1.872849  2.0  3.306306
2019-03-03 -0.977186 -1.290723  1.237134  0.368365  NaN -2.267910
2019-03-04 -0.791070  0.664261  2.141459 -1.416075  NaN -0.126808
2019-03-05 -0.810448  0.064461  0.129514  0.635390  NaN -0.745988
2019-03-06  1.073196 -0.817408  0.386553  0.126255  NaN  0.255788